/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { createContext, useContext, useState, ReactNode } from "react";

type Language = "zh" | "en";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  zh: {
    "nav.home": "首页",
    "nav.gameplay": "玩法介绍",
    "nav.support": "支持",
    "nav.privacy": "隐私政策",
    "nav.terms": "用户协议",
    "nav.download": "下载",
    "hero.tag": "全新策略记忆游戏",
    "hero.title": "五行战将 (Wuxing Zhanjiang)",
    "hero.desc": "基于麻将牌型与五行系统、功能牌增益的记忆与策略小游戏。采用独特的手绘涂鸦艺术风格，融合卡牌选择、牌型识别、商店与多种功能牌，挑战你的记忆极限。",
    "hero.learnMore": "了解玩法",
    "hero.downloadOn": "Download on the",
    "features.title": "核心特色",
    "features.desc": "五行战将 结合了传统麻将的博大精深与现代策略游戏的爽快感。",
    "feature1.title": "记忆与策略",
    "feature1.desc": "在有限的出牌与弃牌次数内，通过选牌、出牌累计分数，挑战 24 个难度递增的关卡。",
    "feature2.title": "五行 (Wuxing) 系统",
    "feature2.desc": "金、木、水、火、土五种元素，通过特定组合对分数施加高额倍数奖励。",
    "feature3.title": "功能牌增益",
    "feature3.desc": "在商店购买「COPY忍术」、「九九归一」、「黄袍加身」等强力功能牌，获得倍数、基础分、花色复制等多种强力增益。",
    "highlight.tag": "核心机制",
    "highlight.title": "五行相生相克，策略无穷无尽。",
    "highlight.desc": "独立的五行槽可容纳最多 5 个元素。出牌时按组合规则对 Base/Multiplier 施加系数。高倍奖励与部分惩罚/删牌组合并存，每一次出牌都需深思熟虑。",
    "highlight.item1": "金 🏅、木 🪵、水 💦、火 🔥、土 🌏 独立五行槽",
    "highlight.item2": "通过「五行」类功能牌向槽内添加元素",
    "highlight.item3": "计分动画实时展示五行加成与视觉反馈",
    "cta.title": "准备好挑战你的记忆了吗？",
    "cta.desc": "立即下载 五行战将，开启你的策略麻将之旅。",
    "cta.button": "立即下载",
    "cta.link": "遇到问题？联系我们",
    "footer.desc": "基于麻将牌型与五行系统、功能牌增益的记忆与策略小游戏。融合卡牌选择、牌型识别、商店与多种功能牌，带给你全新的策略体验。",
    "footer.links": "快速链接",
    "footer.legal": "合规信息",
    "footer.age": "适合年龄: 4+",
    "footer.noRealMoney": "内含虚拟游戏币，无真钱交易",
    "gameplay.title": "玩法介绍",
    "gameplay.desc": "五行战将 是一款融合了麻将牌型、记忆力与策略选择的小游戏。通过合理的选牌与功能牌增益，在有限的次数内达到目标分数。",
    "gameplay.goal.title": "核心目标",
    "gameplay.goal.desc": "每关有最多 4 次出牌机会和 3 次弃牌机会。通过出牌累计分数，达到当前关卡的目标分数即可过关。游戏共 24 关，目标分数从 10 增长至 10,000,000。",
    "gameplay.formula.title": "计分公式",
    "gameplay.formula.main": "最终分数 = 基础分 (Base) × 倍数 (Multiplier)",
    "gameplay.formula.desc": "Base 由固定基础、牌型加成、牌面点数和功能牌加成组成。Multiplier 由牌型倍数和功能牌倍数叠加。五行系统将在最终结算时对两者施加系数。",
    "gameplay.types.title": "牌型一览",
    "gameplay.types.desc": "常见的牌型包括但不限于：",
    "gameplay.wuxing.title": "五行 (Wuxing) 系统",
    "gameplay.wuxing.desc": "这是 五行战将 的核心卖点。独立的五行槽最多可容纳 5 个元素。",
    "gameplay.wuxing.intro": "每次点击出牌时，系统先根据当前槽内元素种类与数量判定是否命中组合。命中后，本手最终 Base、Multiplier 会在牌型与功能牌结算结果上，再乘以对应的五行系数。",
    "gameplay.wuxing.table.title": "五行组合一览",
    "gameplay.wuxing.rules.2": "2张组合",
    "gameplay.wuxing.rules.3": "3张组合",
    "gameplay.levels.title": "关卡目标分数 (24 关)",
    "gameplay.levels.level": "关卡",
    "gameplay.levels.target": "目标分数",
    "gameplay.wuxing.rules.4": "4张组合",
    "gameplay.wuxing.rules.5": "5张组合",
    "gameplay.wuxing.rule.gold1": "仅 1 张且为金: +5 金币 (无系数)",
    "gameplay.wuxing.rule.woodfire": "木 + 火: Multiplier ×20",
    "gameplay.wuxing.rule.goldwater": "金 + 水: Multiplier ×25",
    "gameplay.wuxing.rule.waterfire": "水 + 火: Base/Mult ×0.1 (移除元素)",
    "gameplay.wuxing.rule.goldwood": "金 + 木: Base/Mult ×0.5 (移除元素)",
    "gameplay.wuxing.rule.1w2f": "1木 2火: Mult ×40",
    "gameplay.wuxing.rule.1g2w": "1金 2水: Mult ×50",
    "gameplay.wuxing.rule.3fw": "三火 或 三水: Mult ×66",
    "gameplay.wuxing.rule.3mt": "三木 或 三土: Base ×66",
    "gameplay.wuxing.rule.wft": "木 + 火 + 土: Base/Mult ×33",
    "gameplay.wuxing.rule.wf_penalty": "1水2火 或 1火2水: ×0.01 (移除水火)",
    "gameplay.wuxing.rule.gw_penalty": "两金一木 或 两木一金: ×0.5 (移除金木)",
    "gameplay.wuxing.rule.4wf": "两木两火: Mult ×80",
    "gameplay.wuxing.rule.4gw": "两金两水: Mult ×100",
    "gameplay.wuxing.rule.4fw": "四火 或 四水: Mult ×99",
    "gameplay.wuxing.rule.4m": "四木: Base ×100",
    "gameplay.wuxing.rule.4t": "四土: Base ×101",
    "gameplay.wuxing.rule.5wf": "三木两火 或 三火两木: Mult ×180",
    "gameplay.wuxing.rule.5gw": "三金两水 或 三水两金: Mult ×199",
    "gameplay.wuxing.rule.5f": "五火: Mult ×188",
    "gameplay.wuxing.rule.5s": "五水: Mult ×191",
    "gameplay.wuxing.rule.5w": "五木: Base ×200",
    "gameplay.wuxing.rule.5t": "五土: Base ×191",
    "gameplay.wuxing.rule.5_penalty": "三水两火 或 三火两水: ×0.01 (移除水火)",
    "gameplay.wuxing.item1": "通过「五行」类功能牌向槽内添加元素",
    "gameplay.wuxing.item2": "出牌时按组合规则对分数施加系数",
    "gameplay.wuxing.item3": "包含高倍奖励与部分惩罚/删牌组合",
    "gameplay.shop.title": "商店与功能牌系统",
    "gameplay.shop.desc": "通关奖励 20 金币。金币可用于在商店购买功能牌、刷新商品 (2金) 或在局内紧急开启商店 (10金)。商品数量随槽位上限增加 (2-4个)。",
    "gameplay.shop.permanent.title": "常驻功能牌",
    "gameplay.shop.permanent.desc": "购买后永久生效（除非被替换），例如「COPY忍术」可复制上一次出牌的增益，「好事成双」提供双倍结算加成。",
    "gameplay.shop.consumable.title": "一次性功能牌",
    "gameplay.shop.consumable.desc": "使用后即消失，例如「魂飞魄散」可重置当前手牌，「牛气冲天」在关键时刻提供爆发性基础分加成。",
    "gameplay.joker.copy": "复制忍者 (Copy Ninja)",
    "gameplay.joker.double": "好事成双 (Double Blessings)",
    "gameplay.joker.nine": "九九归一 (All Returns to One)",
    "gameplay.joker.robe": "黄袍加身 (Imperial Robe)",
    "gameplay.joker.soul": "魂飞魄散 (Soul Disperse)",
    "gameplay.joker.bull": "牛气冲天 (Bullish Spirit)",
    "gameplay.joker.thunder": "五雷轰顶 (Thunder Strike)",
    "gameplay.joker.thief": "顺手牵羊 (Handy Thief)",
    "gameplay.joker.lucky7": "幸运7 (Lucky 7)",
    "gameplay.joker.fivegates": "五门丰登 (Five Gates)",
    "gameplay.joker.isize": "iSize-Plus/Pro",
    "gameplay.achievements.title": "成就与排行",
    "gameplay.achievements.desc": "游戏支持本地与 Game Center 排行榜。你可以与全球玩家比拼最高得分，解锁各种趣味成就。",
    "support.title": "支持与联系",
    "support.desc": "遇到问题或有任何建议？我们随时为您提供帮助。",
    "support.contact.title": "联系邮箱",
    "support.contact.desc": "请在邮件中注明您的设备型号、iOS 版本以及问题的详细描述。",
    "support.dev.title": "开发者信息",
    "support.dev.name": "开发者",
    "support.dev.product": "产品：五行战将",
    "support.faq.title": "常见问题 (FAQ)",
    "support.legal.title": "合规声明",
    "support.legal.desc": "本 App 严格遵守 Apple 的 App Store 审核准则。游戏内所有虚拟物品均不可兑换为真实货币。Apple Inc. 非本 App 的赞助方，亦不以任何方式参与本 App 提供的任何活动。",
    "privacy.title": "隐私政策",
    "privacy.lastUpdated": "最后更新日期",
    "privacy.s1.title": "1. 关于本网站",
    "privacy.s1.desc": "本网站为五行战将的官方展示页面。作为一个纯静态展示站，本站本身不收集任何个人数据，不使用 Cookie 进行用户分析。我们仅使用托管方提供的标准访问日志，这些数据仅用于维护网站安全与性能。",
    "privacy.s2.title": "2. 关于 App 端数据收集",
    "privacy.s2.desc": "五行战将 是一款单机向的记忆与策略小游戏。我们高度重视您的隐私，以下是关于 App 端数据处理的详细说明：",
    "privacy.s2.item1": "本地存储：您的游戏进度、金币数量及设置均存储在您的设备本地。我们不会将这些数据上传到我们的服务器。",
    "privacy.s2.item2": "Game Center：如果您启用了 Apple Game Center，您的排行榜分数与成就数据将同步至 Apple 的服务器。这些数据的收集与处理受 Apple 隐私政策的约束。",
    "privacy.s2.item3": "虚拟货币：游戏内使用的金币为虚拟道具，仅用于游戏内逻辑，不涉及真实货币交易，也不收集您的支付信息。",
    "privacy.s2.item4": "第三方 SDK：当前版本的 App 不包含任何第三方广告或分析 SDK。",
    "privacy.s3.title": "3. 数据安全",
    "privacy.s3.desc": "由于游戏数据主要存储在您的设备本地，其安全性主要取决于您对设备的保护。我们建议您定期备份设备，以防数据丢失。",
    "privacy.s4.title": "4. 政策更新",
    "privacy.s4.desc": "我们可能会不时更新本隐私政策。任何更改都将发布在本页面上。建议您定期查看本政策以了解最新的隐私实践。",
    "privacy.s5.title": "5. 联系我们",
    "privacy.s5.desc": "如果您对本隐私政策或我们的隐私实践有任何疑问，请通过以下方式联系我们：",
    "terms.title": "用户协议",
    "terms.s1.title": "1. 软件许可",
    "terms.s1.desc": "本协议是您（用户）与开发者之间关于下载、安装和使用 五行战将 的法律协议。本软件许可为最终用户许可性质，您仅获得非独占、不可转让的有限使用权。",
    "terms.s2.title": "2. 虚拟物品与金币",
    "terms.s2.desc": "本软件内包含虚拟金币等虚拟物品。请注意：",
    "terms.s2.item1": "非货币性质：虚拟金币仅用于游戏内逻辑，不具有任何现实货币价值。",
    "terms.s2.item2": "不可兑换：虚拟金币及任何虚拟物品均不可兑换为真实货币或实物奖品。",
    "terms.s2.item3": "所有权：虚拟物品的所有权归开发者所有，用户仅在游戏内享有使用权。",
    "terms.s3.title": "3. 用户行为规范",
    "terms.s3.desc": "用户在使用本软件时应遵守以下规范：",
    "terms.s3.item1": "不得利用本软件进行任何形式的作弊、滥用或干扰正常游戏秩序。",
    "terms.s3.item2": "不得对本软件进行反向工程、反编译或试图获取源代码。",
    "terms.s3.item3": "不得利用本软件发布违法、违规或侵犯他人权益的内容。",
    "terms.s4.title": "4. 免责声明",
    "terms.s4.desc": "本软件按“现状”提供，不提供任何形式的明示或暗示保证。",
    "terms.s4.item1": "Apple 免责：Apple Inc. 非本 App 的赞助方，亦不以任何方式参与本 App 提供的任何活动。",
    "terms.s4.item2": "责任限制：在法律允许的最大范围内，开发者不对因使用本软件而产生的任何直接或间接损失承担责任。",
    "terms.s5.title": "5. 适用法律",
    "terms.s5.desc": "本协议受开发者所在地法律管辖。如发生争议，双方应友好协商解决；协商不成的，应提交至开发者所在地有管辖权的法院。",
    "terms.s6.title": "6. 其他条款",
    "terms.s6.desc": "如果本协议中的任何条款被判定为无效或不可执行，该条款应在最小必要范围内被删除或限制，且不影响其他条款的有效性。"
  },
  en: {
    "nav.home": "Home",
    "nav.gameplay": "Gameplay",
    "nav.support": "Support",
    "nav.privacy": "Privacy",
    "nav.terms": "Terms",
    "nav.download": "Download",
    "hero.tag": "New Strategy Memory Game",
    "hero.title": "Wuxing Zhanjiang",
    "hero.desc": "A memory and strategy game based on Mahjong patterns, Wuxing system, and Function Card buffs. Featuring a unique hand-drawn doodle art style, it combines card selection, pattern recognition, shop items, and various buffs to challenge your limits.",
    "hero.learnMore": "Learn More",
    "hero.downloadOn": "Download on the",
    "features.title": "Core Features",
    "features.desc": "Wuxing Zhanjiang combines the depth of traditional Mahjong with the excitement of modern strategy games.",
    "feature1.title": "Memory & Strategy",
    "feature1.desc": "Accumulate scores by selecting and playing cards within limited turns and discards across 24 levels.",
    "feature2.title": "Wuxing System",
    "feature2.desc": "Five elements: Gold, Wood, Water, Fire, and Earth. Apply high multipliers through specific combinations.",
    "feature3.title": "Function Card Buffs",
    "feature3.desc": "Purchase powerful Function Cards like 'Copy Ninjutsu', 'All Returns to One', or 'Imperial Robe' in the shop for multipliers, base scores, and more.",
    "highlight.tag": "Core Mechanism",
    "highlight.title": "Wuxing Synergy, Endless Strategy.",
    "highlight.desc": "Independent Wuxing slots hold up to 5 elements. Apply coefficients to Base/Multiplier based on combination rules. High rewards and penalties coexist.",
    "highlight.item1": "Gold 🏅, Wood 🪵, Water 💦, Fire 🔥, Earth 🌏 slots",
    "highlight.item2": "Add elements via Wuxing Function Cards",
    "highlight.item3": "Real-time visual feedback for Wuxing bonuses",
    "cta.title": "Ready to challenge your memory?",
    "cta.desc": "Download Wuxing Zhanjiang now and start your strategic Mahjong journey.",
    "cta.button": "Download Now",
    "cta.link": "Need help? Contact us",
    "footer.desc": "A memory and strategy game based on Mahjong patterns, Wuxing system, and Function Card buffs. Experience a new level of strategy.",
    "footer.links": "Quick Links",
    "footer.legal": "Legal",
    "footer.age": "Age: 4+",
    "footer.noRealMoney": "Virtual currency only, no real money gambling",
    "gameplay.title": "Gameplay",
    "gameplay.desc": "Wuxing Zhanjiang blends Mahjong patterns, memory, and strategic choices. Reach target scores through clever card selection and Function Card buffs.",
    "gameplay.goal.title": "Core Goal",
    "gameplay.goal.desc": "Up to 4 plays and 3 discards per level. Reach the target score to progress. 24 levels with increasing difficulty (10 → 10,000,000).",
    "gameplay.formula.title": "Scoring Formula",
    "gameplay.formula.main": "Final Score = Base × Multiplier",
    "gameplay.formula.desc": "Base consists of fixed base, pattern bonus, card points, and card buffs. Multiplier stacks from pattern and card buffs. Wuxing system applies coefficients at final scoring.",
    "gameplay.types.title": "Pattern List",
    "gameplay.types.desc": "Common patterns include but are not limited to:",
    "gameplay.wuxing.title": "Wuxing System",
    "gameplay.wuxing.desc": "The core selling point. Independent slots hold up to 5 elements.",
    "gameplay.wuxing.intro": "When playing cards, the system checks the elements in the slots. If a combination matches, the Base and Multiplier are multiplied by the corresponding coefficients.",
    "gameplay.wuxing.table.title": "Wuxing Combinations",
    "gameplay.wuxing.rules.2": "2-Card Combos",
    "gameplay.wuxing.rules.3": "3-Card Combos",
    "gameplay.levels.title": "Target Scores (24 Levels)",
    "gameplay.levels.level": "Level",
    "gameplay.levels.target": "Target Score",
    "gameplay.wuxing.rules.4": "4-Card Combos",
    "gameplay.wuxing.rules.5": "5-Card Combos",
    "gameplay.wuxing.rule.gold1": "1 Gold: +5 Gold Coins (No coefficient)",
    "gameplay.wuxing.rule.woodfire": "Wood + Fire: Multiplier ×20",
    "gameplay.wuxing.rule.goldwater": "Gold + Water: Multiplier ×25",
    "gameplay.wuxing.rule.waterfire": "Water + Fire: Base/Mult ×0.1 (Remove elements)",
    "gameplay.wuxing.rule.goldwood": "Gold + Wood: Base/Mult ×0.5 (Remove elements)",
    "gameplay.wuxing.rule.1w2f": "1W 2F: Mult ×40",
    "gameplay.wuxing.rule.1g2w": "1G 2W: Mult ×50",
    "gameplay.wuxing.rule.3fw": "3 Fire or 3 Water: Mult ×66",
    "gameplay.wuxing.rule.3mt": "3 Wood or 3 Earth: Base ×66",
    "gameplay.wuxing.rule.wft": "Wood + Fire + Earth: Base/Mult ×33",
    "gameplay.wuxing.rule.wf_penalty": "1W 2F or 1F 2W: ×0.01 (Remove Water/Fire)",
    "gameplay.wuxing.rule.gw_penalty": "2G 1W or 2W 1G: ×0.5 (Remove Gold/Wood)",
    "gameplay.wuxing.rule.4wf": "2 Wood 2 Fire: Mult ×80",
    "gameplay.wuxing.rule.4gw": "2 Gold 2 Water: Mult ×100",
    "gameplay.wuxing.rule.4fw": "4 Fire or 4 Water: Mult ×99",
    "gameplay.wuxing.rule.4m": "4 Wood: Base ×100",
    "gameplay.wuxing.rule.4t": "4 Earth: Base ×101",
    "gameplay.wuxing.rule.5wf": "3W 2F or 3F 2W: Mult ×180",
    "gameplay.wuxing.rule.5gw": "3G 2W or 3W 2G: Mult ×199",
    "gameplay.wuxing.rule.5f": "5 Fire: Mult ×188",
    "gameplay.wuxing.rule.5s": "5 Water: Mult ×191",
    "gameplay.wuxing.rule.5w": "5 Wood: Base ×200",
    "gameplay.wuxing.rule.5t": "5 Earth: Base ×191",
    "gameplay.wuxing.rule.5_penalty": "3W 2F or 3F 2W: ×0.01 (Remove Water/Fire)",
    "gameplay.wuxing.item1": "Add elements via Wuxing Function Cards",
    "gameplay.wuxing.item2": "Apply coefficients based on combination rules",
    "gameplay.wuxing.item3": "Includes high rewards and penalty combinations",
    "gameplay.shop.title": "Shop & Function Card System",
    "gameplay.shop.desc": "Earn 20 gold per win. Use gold to buy cards, reroll shop (2g), or open shop during a level (10g). Item count increases with slot limit (2-4 items).",
    "gameplay.shop.permanent.title": "Permanent Function Cards",
    "gameplay.shop.permanent.desc": "Last forever unless replaced. For example, 'Copy Ninjutsu' can copy previous buffs, and 'Double Blessings' provides double scoring bonuses.",
    "gameplay.shop.consumable.title": "Consumable Function Cards",
    "gameplay.shop.consumable.desc": "Disappear after use. For example, 'Soul Disperse' can reset your hand, and 'Bullish Spirit' provides a burst of base score at critical moments.",
    "gameplay.joker.copy": "Copy Ninja",
    "gameplay.joker.double": "Double Blessings",
    "gameplay.joker.nine": "All Returns to One",
    "gameplay.joker.robe": "Imperial Robe",
    "gameplay.joker.soul": "Soul Disperse",
    "gameplay.joker.bull": "Bullish Spirit",
    "gameplay.joker.thunder": "Thunder Strike",
    "gameplay.joker.thief": "Handy Thief",
    "gameplay.joker.lucky7": "Lucky 7",
    "gameplay.joker.fivegates": "Five Gates",
    "gameplay.joker.isize": "iSize-Plus/Pro",
    "gameplay.achievements.title": "Achievements & Rankings",
    "gameplay.achievements.desc": "Supports local and Game Center leaderboards. Compete globally and unlock fun achievements.",
    "support.title": "Support & Contact",
    "support.desc": "Have questions or suggestions? We're here to help.",
    "support.contact.title": "Contact Email",
    "support.contact.desc": "Please include your device model, iOS version, and a detailed description of the issue.",
    "support.dev.title": "Developer Info",
    "support.dev.name": "Developer",
    "support.dev.product": "Product",
    "support.faq.title": "FAQ",
    "support.legal.title": "Compliance",
    "support.legal.desc": "This App strictly follows Apple's App Store Review Guidelines. All virtual items are non-redeemable for real currency. Apple Inc. is not a sponsor of this App.",
    "privacy.title": "Privacy Policy",
    "privacy.lastUpdated": "Last Updated",
    "privacy.s1.title": "1. About this Website",
    "privacy.s1.desc": "This website is the official showcase for Wuxing Zhanjiang. As a static site, it does not collect personal data or use cookies for analysis. We only use standard server logs for security and performance.",
    "privacy.s2.title": "2. App Data Collection",
    "privacy.s2.desc": "Wuxing Zhanjiang is a single-player strategy game. We value your privacy. Here is how we handle your data:",
    "privacy.s2.item1": "Local Storage: Your progress and gold are stored locally on your device. We do not upload this to our servers.",
    "privacy.s2.item2": "Game Center: If enabled, your scores and achievements are synced with Apple's servers, subject to Apple's privacy policy.",
    "privacy.s2.item3": "Virtual Currency: Gold is a virtual item for game logic only. No real money transactions or payment data collection.",
    "privacy.s2.item4": "Third-party SDKs: Current version contains no third-party ads or analysis SDKs.",
    "privacy.s3.title": "3. Data Security",
    "privacy.s3.desc": "Since data is stored locally, security depends on your device protection. We recommend regular backups.",
    "privacy.s4.title": "4. Policy Updates",
    "privacy.s4.desc": "We may update this policy. Changes will be posted here. Please check regularly.",
    "privacy.s5.title": "5. Contact Us",
    "privacy.s5.desc": "If you have questions about our privacy practices, please contact us:",
    "terms.title": "Terms of Use",
    "terms.s1.title": "1. Software License",
    "terms.s1.desc": "This agreement is between you and the developer regarding Wuxing Zhanjiang. This is a limited, non-exclusive, non-transferable license for end-users.",
    "terms.s2.title": "2. Virtual Items",
    "terms.s2.desc": "The software contains virtual gold and items. Please note:",
    "terms.s2.item1": "Non-monetary: Virtual gold has no real-world monetary value.",
    "terms.s2.item2": "Non-redeemable: Items cannot be exchanged for real money or prizes.",
    "terms.s2.item3": "Ownership: All virtual items are owned by the developer; users have a right to use them in-game.",
    "terms.s3.title": "3. User Conduct",
    "terms.s3.desc": "Users must follow these rules:",
    "terms.s3.item1": "No cheating, abuse, or interference with game order.",
    "terms.s3.item2": "No reverse engineering or attempting to obtain source code.",
    "terms.s3.item3": "No posting illegal or infringing content through the software.",
    "terms.s4.title": "4. Disclaimer",
    "terms.s4.desc": "The software is provided 'as is' without warranties.",
    "terms.s4.item1": "Apple Disclaimer: Apple Inc. is not a sponsor and is not involved in any way.",
    "terms.s4.item2": "Liability: Developer is not liable for direct or indirect losses from using the software.",
    "terms.s5.title": "5. Governing Law",
    "terms.s5.desc": "Governing law is that of the developer's location. Disputes shall be settled through negotiation or in local courts.",
    "terms.s6.title": "6. Miscellaneous",
    "terms.s6.desc": "If any term is invalid, it shall be removed without affecting the rest of the agreement."
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>("en");

  const t = (key: string) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
